### ISSUE TITLE
Fix debug mode only working on first game of batch

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/meteor-empirica-core#12]
selecting a complete randomization with more than one treatment and starting the batch in debug mode will enter the debug mode for only one of the games, but not all the games in the batch.

**Comment by amaatouq** [comment]
they will all have the long timer, but skipping the instructions will happen only for one.

**Comment by npaton** [comment]
The way debug mode is implemented is super sketchy. I tried to figure out this issue without success. I think it would be best to not fix this issue now, and wait for the rewrite of debug mode, which I've been planning since debug mode was thrown together. We can keep this ticket to track the issue in any case.

But let me know if this is very harming and really needs a near term fix.

**Comment by amaatouq** [comment]
No, not a big deal for now! It can wait.
