### ISSUE TITLE
Query Targeting: Scanned Objects / Returned has gone above 1000

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/meteor-empirica-core#126]
I had this issue in my inbox this morning:
![image](https://user-images.githubusercontent.com/4304478/81292569-d0de8100-9039-11ea-9314-a68a55ba89cf.png)
I'm not sure if it means I'm doing something wrong, or if I just have a big database?

There's not really that much going on:
![image](https://user-images.githubusercontent.com/4304478/81292678-071c0080-903a-11ea-92ad-4ef74c069425.png)

I could clear out the data, it's just old games that don't need to be stored on the server. But there is plenty of storage on the server, making me think maybe I'm doing something wrong somewhere else...

I'm on empirica@ https://github.com/empiricaly/meteor-empirica-core/commit/92903252bdda34ddd62aade459a580517dc87565

**Comment by npaton** [comment]
It is a side-effect of how Meteor works, and it should not cause any issues. It’s a warning for something that is not an actual problem in our context. It has to do with Meteor reading the Mongo oplog, which is a capped collection with all document changes, and that can’t take indexes ; Meteor uses that collection to reactively synchronize data, which requires scanning documents, which in itself is considered slow, and should require an index, but in the case it doesn’t actually matter because the database is not overloaded, and this query does not happen frequently, nor is very time sensitive. This scanning issue would be a problem if it were to affect initial queries, which it doesn’t, all queries have indexes. So all good.

We can safely disable the notification though (Empirica has indexes, though if you have your own Mongo tables that do not have proper indexes). Go to you Project > Alerts > Alert Settings, and look for the line saying "Query Targeting:…”, and disable it.

**Comment by JamesPHoughton** [comment]
Thanks!
