### ISSUE TITLE
Players obtained from game.getPlayers() do not function the same as the player prop (no .get())

### ISSUE THREAD

**Issue by Karakaii** [empiricaly/meteor-empirica-core#211]
In the `callbacks.js`, in `Empirica.onStageEnd`, I am trying to get and set information to a player. The `player `isn't a parameter of this callback, but we can get the Players with `game.getPlayers()`. However, these players do not function the same way as `player `as a prop; you cannot use `.get()` and `.set()`. I would suppose that it should be more consistent. I can access the information by getting the `player.data`. I suppose I can set it there and it might update the `player` prop, but I am not sure. If there is a way of making this consistent with how it works with the props (and, see below, how it worked before).
This is with `empirica:core 1.13.0 `

I have another project, with` empirica:core 1.11.1` where I could successfully use `game.players` to access the players, and where once I selected the players I could use `.get()` and `.set()`. Although this was not in a _callback_, I don't see why it would be different? 
I think `game `was changed? 

Thank you for your help.

**Comment by npaton** [comment]
`game.getPlayers()` is an internal/private API. You should always use `game.players`. I apologize for the confusion. In order to remove the possibility for mistake here, we are removing `game.getPlayers()`. If anyone is using this API, please change your code to use `game.players`. This is a breaking change if you were using the internal API. Our apologies for the misleading API and lacking documentation.

@hubertusputu1  Once the private API is removed, make sure to announce it to people who might have encountered the issue in the following thread: https://empirica-ly.slack.com/archives/C0166DAMN7N/p1611928107001400

**Comment by npaton** [comment]
Marking this one as open until it is reported on in Slack to people who might be affected. 👍

**Comment by Karakaii** [comment]
My apologies, for some reason I was convinced that `game.players` did not work, but it seems like it does. I must have had a typo or small mistake and then I saw `.getPlayer()` and thought that things had changed... Thank you for looking into this!

**Comment by npaton** [comment]
@Karakaii No problem, the API isn't very clear, we really need to document it better. 👍

**Comment by npaton** [comment]
I will close this since @Karakaii has relayed the info on the aforementioned thread. Note, not deployed, will be later today.
