### ISSUE TITLE
Lock factor types

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/meteor-empirica-core#23]
do we need to add a new factor type, which requires defining "allowed values"? 

(i.e., allowedValues: ["stationary", "nonStationary", "semiStationary"])

**Comment by npaton** [comment]
I actually implemented that initially, and it was a bunch of work. Then realised it was exactly the same as a string typed factor, expect you couldn't add anymore factor values.

So maybe instead we can add locking to factors to have the same effect, with the added value that it works with any type. And with an option to unlock because I'm sure that's something people will eventually want to do.

**Comment by amaatouq** [comment]
> I actually implemented that initially, and it was a bunch of work. Then realised it was exactly the same as a string typed factor, expect you couldn't add anymore factor values.
> 
> So maybe instead we can add locking to factors to have the same effect, with the added value that it works with any type. And with an option to unlock because I'm sure that's something people will eventually want to do.

yes, 💯  right! this is not a high priority though!

**Comment by npaton** [comment]
I think this is no longer relevant.
