### ISSUE TITLE
between init & round (no experiments) is shown

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/meteor-empirica-core#4]
after the lobby is filled and before the game starts, we used to have a screen telling players that we are loading the game. Now it shows 'no experiments available' and then the game starts.

**Comment by amaatouq** [comment]
aah this is only for the last player to enter the game .. the rest see the loading page.

**Comment by npaton** [comment]
This should be fixed with the next update.

**Comment by amaatouq** [comment]
I think this issue can prevent running experiments— given that the game loading takes around 40 seconds and the last player to join the game doesn’t see the loading page but the acreen freezes on the quiz and then they see no experiment available until the game starts. Several people in a pilot today closed their browser during that and did not play thinking there are no experiments.

**Comment by npaton** [comment]
This should be fixed with `empirica:core` v0.0.6.

@amaatouq The 40s to create a game is absurdly slow, could you create a ticket for that and point me to the code that produces this issue. Thanks.

**Comment by amaatouq** [comment]
I will do that after I benchmark it again. These things are happening in the `guess the correlation` experiment with 20 rounds and 12 players.

**Comment by joshua-a-becker** [comment]
any update on this particular issue, re: game init time, is there a ticket?  i'd like to follow and maybe help, on occasion i have clever ideas about code efficiency  (if not already resolved).  also think it might be related to https://github.com/empiricaly/meteor-empirica-core/issues/39

**Comment by npaton** [comment]
@joshua-a-becker I don't think there's a ticket for long game init time. Feel free to add it. If you have an idea how to improve that issue, after you opened the issue, please add a comment explaining how you are thinking about improving on it, so we can discuss changes before you get too deep into a fix that might not work with future developments. FYI, the issue hasn't been addressed yet because it is quite complicated to resolve, there are so many thing happening, and the order of operations is important. Also, with the upcoming new assignment, things might be changing in and around game init. But always happy to hear new idea for improvement!!
