### ISSUE TITLE
add a method to get only bots.

### ISSUE THREAD

**Issue by eamanj** [empiricaly/meteor-empirica-core#43]
It would be nice to have a method that returns list of bots in the game, rather than just looping over players and extracting the bots. a one-liner like this:

`return _.filter(game.players, p => 'bot' in p);`

**Comment by eamanj** [comment]
same for human players: 
`
return _.reject(game.players, p => 'bot' in p);`

**Comment by npaton** [comment]
I am not sure about this. I do understand it might be somewhat helpful but I want to be careful to not grow the API for things that are really simple to do. I do not find the following too hard to do:

Bots: `game.players.filter(p => p.bot)`
Humans: `game.players.filter(p => !p.bot)`

But I am bias here obviously. The problem with adding methods for this to the `game` object to me, beyond cluttering the API, is that wherever there's a list of players available, these methods should exist as well, which amplifies yet again the API. To be fair, I'm not sure where else a list of players is available at this point, but there will be other places without a doubt.

I feel like educating the game designers about the API, knowing that the bot field will tell you that it's a bot is more flexible and light. It can be used in more situations (like iterating over all players, bots or not), while also serving as indicating which bot we're dealing with when it's a bot.

It is also quite simple to make helper methods if this is a recurring problem for you: 

```js
const bots = players => players.filter(p => p.bot);
bots(game.players).forEach( ...
```

All of that said, I am not completely against this either. I will keep it in mind. The whole bots system is in it's early days, and will probably get vastly improved at some point, and something like this might be a valuable addition to the API.

Sorry for the long response for something that seems so small, but I will always try to push back on API changes until I am convinced otherwise, in order to try and maintain the simplicity of the API.

Side note, the method you are using with `'bot' in p` should generally work, but it is less reliable to test the presence of the key (`'key' in object`) than testing for a falsy value (`object.key`). If the value where anything falsy but were present (for whatever reason), the key test would mistakenly return true.
