### ISSUE TITLE
same game gets assigned to multiple gameIds

### ISSUE THREAD

**Issue by chri4354** [empiricaly/meteor-empirica-core#48]
We noticed some weirdness in the data files exported. If you open the games.csv file, the last two games are `7nhhYSuAcpvEhG2pB` and `i23BepCfrCgspwgmR`. If you scroll over to the 'playerIds' column, these two games have identical lists of playerIds. And they were started at the same time. Then if you open `player-rounds.csv` you can see these two games have the same batchId `6vNYeAnAEoeY4Fjes`, but they have different round Ids.

**Comment by npaton** [comment]
I have looked into this issue and I have not yet found an evident cause for it.

I do think it has to do with the fact that Meteor every mutation in Meteor should be idempotent, which we currently do not fully support, notably because it can be difficult to do with Mongo, which does not have transactions. So if some things are called twice (an a meteor method, a hook...), code re-executes and double inserts may happen.

The game creation method does have a check to try to avoid this issue, but without transactions on Mongo, the check can sometimes fail. We could try to use upserts and other fun 
Mongo hacks to work around the problem. At least, this is my current reasoning. Some of these issues will be resolved in the current rearchitecture we are working on.

It does seem though, while in the export the doubled game is a problem, like it does not to interfere with the running games, so I am not immediately prioritizing it, and counting on the rearchitecture to try and fix this issue.

**Comment by npaton** [comment]
I believe this is something that was fixed and we haven't heard about again, please reopen if you see this issue again.
