### ISSUE TITLE
onNext does not work in exit steps

### ISSUE THREAD

**Issue by eamanj** [empiricaly/meteor-empirica-core#58]
Just confirmed with Abdullah that onNext() is missing in exit steps. I have an exit pipeline with 3 steps, and having this.props.onNext(); in handleSubmit() does not do anything.

**Comment by npaton** [comment]
I agree, `onSubmit` should be called `onNext` like it does in the intro steps. At this point, I do not want to change the API though, as it would break apps already deployed, but it will be fixed in a later major update.

`onSubmit` does work in all my tests. Maybe it's a name issue if you are using `handleSubmit` instead of `onSubmit`?

I am closing this issue for now, and note that the API inconsistency here is well known and expected to be fixed along with others in a later major release. Reopen if with further details if you are still seeing a problem here.
