### ISSUE TITLE
set ExitStatus in onGameEnd

### ISSUE THREAD

**Issue by eamanj** [empiricaly/meteor-empirica-core#60]
player.exitStatus is undefined in onGameEnd. I think at this point, exitStatus can be set and examined. Any reason it is not set at this point?

**Comment by amaatouq** [comment]
There is no exitStatus yet during `onGameEnd` because the game is still active at this point and players have not exited yet. The game has to end first for the players within it to be assigned an exitStatus. players can have `exitStatus` without belonging to a game (e.g., oth if all games are full, if they waited in the lobby and the game did not start) or because the admin canceled the batch form the admin UI. 

It seems what you are looking for is `Empirica.exitSteps((game, player) => {})` and not `onGameEnd()`
