### ISSUE TITLE
Running on multiple containers

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/meteor-empirica-core#76]
I'm running a 40 player game using galaxy and a mongodb/Atlas backend. I have been overprovisioning both my galaxy instances and my database, because doing so is much cheaper than a failed game. (Found that one out the hard way!) I'm running 3 quad containers on the app, and an M20 cluster for the db.

Talking with @amaatouq today, it sounds like it is surprising that this works (as empirica is single-threaded?). I had just assumed that because the separate containers had a shared db, they could coordinate. It does make a difference in performance, as players were having hung games and long wait times at game start and game end with just a single container.
Here's a screenshot of the performance measures on galaxy:

![Galaxy_3xQuad_01](https://user-images.githubusercontent.com/4304478/69756547-c5049f80-1128-11ea-8315-1b1664e3b3aa.png)

![Galaxy_3xQuad_02](https://user-images.githubusercontent.com/4304478/69756561-c9c95380-1128-11ea-92e4-ecc34b213456.png)

Normally I manage to accidentally break things, so accidentally making something work is a new experience for me...

Looks like my usage peaked out at about 4.7ECU

**Comment by npaton** [comment]
Hey @JamesPHoughton. Thank you so much for the feedback!

Indeed, Empirica is not currently well suited to multi-server deployments unfortunately, and it's not something our poor documentation states anywhere yet I think (we have plans to improve documentation).

I'm glad to hear it worked well for you, but I must warn that there could be complications. There could be race conditions (such as concurrent assignment to the same game), and background actions that might happen multiple times (such as callbacks to onStage/RoundEnd), once on each server. The reason we don't support multiple servers is mostly because of some of these background processes that can be duplicated when running on multiple servers (and can sometimes fail to happen at all due to the distributed timer system that tries to do the right thing when deployed on multiple servers, but that can fail, it's not very solid). So we have tried to make things work for multiple servers at points (also there are well know issues such as onChange callbacks), so it could work, and if you're getting good results that's really great (and maybe we should revisit this question), but I cannot guaranty clean execution in such context.

So please let me know if you see any problems during your experiment, and I'd be glad to take a look at things and maybe keep improving Empirica for multi-server use.

As a side note, we'd also like to make Empirica more performance out of the box, we should be able to run a 40 person experiment on a single server without issues (though it can depend on the amount of things the experiment is doing per player).

**Comment by JamesPHoughton** [comment]
Thanks @npaton! Good to have the warnings about what may not work. So far I have only run one game at a time - is that protecting me from having a user assigned multiple times to the same game (and is this what you mean by concurrent assignment?)? Would I be more likely to have issues if I ran multiple games at the same time?

I rely a fair amount on the `player.append()` callback - I log each user action, probably 1500~2000 times over 8 minutes for a 40 person game, and then use the logs to recreate the state of the game. So far (4 pilot games on 3 servers) I haven't had trouble matching the log-recreated state to the recorded game end state, so that may build some confidence. Running 30+ more games over the next few weeks, I'll let you know if i have problems. =)

**Comment by npaton** [comment]
Normally, assignment is protected against concurrency issues, but it's not necessarily a highly reliable mechanism (Mongo does not have transactions, so for assignment in particular we use conditional writes and loop until a write works, though the whole operation is a little more complex than that). And there are a few other places that could have issues for essentially the same reason. You should be able to run multiple concurrent games. All this to say, I am not exactly sure where things might break, if they even do, depending on your experiment. 😄 

I am looking forward to any feedback on your experience!

Note, in a recent release of Empirica (update with `meteor update empirica:core`), we've added a `player.log("key", anyValue)` call, which will be more performant than `append`. `append` will synchronize all data to all players in the same game, which can be slow. If you do not need the data in other player's context, `player.log` just sends the data to the DB and does nothing with it, which is a lot cheaper. The new data is in a new table on export (`player_logs` I believe), the value is encoded as JSON and should still be easy to correlate with stages/rounds. If this works for you, I recommend you try it out thoroughly locally (including the export), as this is a relatively new addition to the API. 👍

**Comment by JamesPHoughton** [comment]
Thanks @npaton, `player.log()` looks like the way to go. I'm being really inefficient at the moment and using `player.set()` to give neighbors access to the player's state, and also `player.append()` to log actions. That'll be for experiment number 2....

**Comment by npaton** [comment]
I am closing this for now. We will be doing work on horizontal scaling this year. ⛵️
