### ISSUE TITLE
"Uncaught Error: Invariant failed" in client errors

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/meteor-empirica-core#82]
Running a game with Galaxy's APM enabled, I see this error reported by two users:

```
Error: Invariant failed
    at i (http://detective.meteorapp.com/a1dfcda0dc4107276e8fa991d200a9d2b0de4589.js?meteor_js_resource=true:9:1007271)
    at Object.e [as startPublishing] (http://detective.meteorapp.com/a1dfcda0dc4107276e8fa991d200a9d2b0de4589.js?meteor_js_resource=true:9:947302)
    at http://detective.meteorapp.com/a1dfcda0dc4107276e8fa991d200a9d2b0de4589.js?meteor_js_resource=true:9:934585
    at http://detective.meteorapp.com/a1dfcda0dc4107276e8fa991d200a9d2b0de4589.js?meteor_js_resource=true:9:942718
    at http://detective.meteorapp.com/a1dfcda0dc4107276e8fa991d200a9d2b0de4589.js?meteor_js_resource=true:9:934975
    at http://detective.meteorapp.com/a1dfcda0dc4107276e8fa991d200a9d2b0de4589.js?meteor_js_resource=true:9:1004611
    at Object.r.onLift (http://detective.meteorapp.com/a1dfcda0dc4107276e8fa991d200a9d2b0de4589.js?meteor_js_resource=true:9:984805)
    at http://detective.meteorapp.com/a1dfcda0dc4107276e8fa991d200a9d2b0de4589.js?meteor_js_resource=true:9:975486
    at e (http://detective.meteorapp.com/a1dfcda0dc4107276e8fa991d200a9d2b0de4589.js?meteor_js_resource=true:9:974891)
    at e (http://detective.meteorapp.com/a1dfcda0dc4107276e8fa991d200a9d2b0de4589.js?meteor_js_resource=true:9:975463)
```

It doesn't seem to have influenced the player's behavior, but it's hard for me to be sure. Is it a big deal?

## Environment
The clients in question were running:
1. Chromium 78 on Ubuntu
2. Chrome 79 on Windows 10

I'm running:
Empirica 1.4.0 
Meteor 1.9.3
Node 13.1.0
all on Galaxy

**Comment by npaton** [comment]
It's hard to tell exactly what's going on from this stack trace. It seems like it might be related to ReactRouter and using <Link> outside <Route>, or different versions of ReactRouter being used at the same time (which shouldn't be happening unless you've made changes to the routing). Do you use a different render root than the default, meaning, did you change the following in `client/main.js`:

```
Meteor.startup(() => {
  render(Empirica.routes(), document.getElementById("app"));
});
```

If not, I am not sure what the problem is. Normally there is 0 navigation happening at all on the player side, the player always stays at `/` (home), so there shouldn't be any routing event. There is routing happening in the admin. Might the issue have happened to you in the admin?

If there have not been any reported experience issue, I cannot tell much more from this, so I will close the ticket for now. If it does not seem to affect players, I would consider this a transient, non-impacting problem that might have to do with a temporary network error. If you get any reports or more detailed info on where the issue might be, please reopen the issue with details.
