### ISSUE TITLE
Performance issues in 0.14.0

### ISSUE THREAD

**Issue by alexhustler** [empiricaly/meteor-empirica-core#84]
When a game has 150 rounds and 15 players the game becomes very slow and unresponsive. This is very similar to the behavior described here https://github.com/empiricaly/meteor-empirica-core/issues/62.

Thanks

**Comment by npaton** [comment]
I have a couple questions to help me understand the problem better. So this is a regression? On that previous issue #62, did you see an improvement after the update I made back then?
Have you tried with a lower set of round, with say 50 or 100 rounds? Are we sure the issue become worse  with the number of rounds?
I will try to run some tests to see if it's something and I can reproduce. Obviously, number of rounds shouldn't affect performance, but we might still have problems there.

**Comment by alexhustler** [comment]
- I'm not sure if it's a regression. I definitely saw improvements after the last performance fixes you made, but there was still some slowness.
- If there are less rounds and less players I don't see the performance issues.

- I've noticed some of the React components are being rendered many times every second. For example the Timer.jsx component can be rendered 20-30 times/second and the TaskStimulus.jsx component is rendered quite often too.

@npaton

**Comment by npaton** [comment]
Thank you Alex. Components do tend to re-render too much for sure. I think there are other problems as well. We will be taking a long look at this in this beginning of next week, I let you know when we have made progress.

**Comment by hubertusputu1** [comment]
Hi @alexhustler , my name is Hubertus. i am here working with @npaton and looking into this problem. I did a certain test with 150 rounds and 15 players, i updated 2 values on each player every 1s. I run the experiment until it reached more than 50 rounds, and it still looked ok without any performance issue that you mentioned previously. Is it possible for us to look into your code and try to reproduce the issue from it? Thank You very much 😃

**Comment by hubertusputu1** [comment]
Hi @alexhustler . Thank you for the access to your repo, i already checked it and was able to reproduce the performance issue. Just for your information, i was able to reproduce it with just a one player. The issue is located on your file `TaskStimulus.jsx` on line 69. Your code try to set the `player.round.set("cueAgreement", roundLocalAccurate === ifp.globalAccurate)` inside a `render()` function, that line of code will create a render loop which make the browser not responding. 

We suggest that do not updating any values inside a `render()` function.

We came up with two solutions that you can try:
1. you can do the updating value on `TaskStimulus.jsx` inside `componentDidMount()` function
2. you can set value on the backend, `server/callback.js` inside `Empirica.onRoundStart()` function. Loop the players and do the updating there. 

Please let us know, if you still face the performance issues, thank you 😃
