### ISSUE TITLE
Slow transition between stages in games with many rounds

### ISSUE THREAD

**Issue by LBrinkmann** [empiricaly/meteor-empirica-core#89]
## Current Behavior
We found transitions between stages running slow (~1500ms) on games with many (>80) rounds. Additionally, we experienced high workloads on the database (>100 queries/s with only 8 games). 
We could trace the issue back to a number of database fetches before a round is finished: 

https://github.com/empiricaly/meteor-empirica-core/blob/f01ca69d3078fc8efd25129a1ac23e3f0cb34d22/api/stages/finish.js#L14-L26

## Solution 
We are working on a solution.

**Comment by npaton** [comment]
Ah, yes, lots of rounds will make loading all of them here, plus all stages, quite slow. We wanted to afford convenience, but it does come at the cost of performance. We do have plans to address this issue in v2 (later in 2020). In v1, since the system does not support multi-server deployments, we could consider a simple local cache for this data. Another solution that has helped increase performance is to collocate Mongo and the app server on the same machine.
Let me know of any solution/improvement you find, and if I can help further.
